{{ if .Values.dfEnabled }}
{{ $values := (. | mustDeepCopy) }}
{{ $_ := set $values "common" (dict "nameSuffix" "df") }}
{{ include "common.deployment.common_config" $values | nindent 0 }}
spec: {{ include "common.deployment.common_spec" $values | nindent 2 }}
  template: {{ include "common.deployment.pod.metadata" $values | nindent 4 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-df
        image: {{ template "df.imageName" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env: {{ include "df.envVariableConfiguration" $values | nindent 10 }}
        volumeMounts: {{ include "df.volumeMountsConfiguration" $values | nindent 10 }}
        ports:
        - name: df-tcp
          containerPort: 8066
          protocol: TCP
      volumes: {{ include "df.volumeConfiguration" $values | nindent 8 }}
{{ end }}